name: oneaction


on:
 push:
   branches:
     - main


jobs:
 body-builder:
   runs-on: ubuntu-latest


   steps:
     - uses: actions/checkout@v2
     - name: Run a one-liner script
       run: echo Hello, world!




 deploy:
   runs-on: ubuntu-latest
   needs: body-builder


   steps:
     - uses: actions/checkout@v2
     - name: Run a one-liner script
       run: echo Hello, world!
